### ISSUE TITLE
stringp, nil error when message-alternative-emails is not set

### ISSUE THREAD

**Issue by chipschap** [girzel/gnorb#23]
In gnorb-org.el, if message-alternative-emails has not been set, then in gnorb-org-extract-email-tracking, there is a failure at (string-match-p message-alternative-emails from).

It took me rather a while to track this one down :) My solution is simply to set message-alternative-mails to an appropriate value in my startup files, although I suppose a check could be added to the gnorb code.

I think gnorb is going to be very useful for me, it's just there have been a lot of little fiddly setup things that I fixed over time by trial and error (for instance, ensuring that all my org-capture templates contained the %a link symbol). But I am stubborn and persistent.

**Comment by girzel** [comment]
Sorry to send you on a hunt! :) And thanks for tracking that down.

That was a dumb assumption on my part, and I'll add some guards there.

I know gnorb is confusing, and I understand why: as "spiderweb code" between several other packages, it's got lots of nooks and crannies and odd particulars. I really need to improve the documentation and examples. If you can share any particular points that caused you difficulty, that would be very helpful!
