### ISSUE TITLE
Package from elpa breaks my emacs start

### ISSUE THREAD

**Issue by marcowahl** [girzel/gnorb#29]
Hi Eric,

Thanks for gnorb.  Still experimenting, but also using it already!

With the latest gnorb update from melpa my Emacs fails to start with the message

`face-spec-recalc: Wrong type argument: listp, org-link   ` `

I intuitively fixed this by changing the defface in gnorb-bbdb.el like

```
(defface gnorb-bbdb-link '((t :inherit org-link))
  "Custom face for displaying message links in the *BBDB* buffer.
  Defaults to org-link."
  :group 'gnorb-bbdb)

```

Hopefully this is a good fix or you know better!

Best regards,  Marco

**Comment by girzel** [comment]
Thanks for the report! I think we've got a fix already in.

**Comment by marcowahl** [comment]
Thanks!
