### ISSUE TITLE
Problem with defface in gnorb-bbdb.el

### ISSUE THREAD

**Issue by berhoel** [girzel/gnorb#30]
The Patch in commit b53c93f8883257d805607d4683dc68055642a918 

```
-(defface gnorb-bbdb-link (org-compatible-face 'org-link nil)
+(defface gnorb-bbdb-link 'org-link
```

does not work for me.

with --dbug-init I get:

```
Debugger entered--Lisp error: (wrong-type-argument listp org-link)
```

`M-x apropos org-link` gives:

```
...
org-link
  Group: Options concerning links in Org mode.
  Face: Face for links.
  Properties: custom-loads group-documentation custom-tag custom-group
              face-defface-spec face-modified face face-documentation
...
```

With my limited elisp knowledge I would assume the `defface` statemet uses the property instead of the face. A change to

```
(defface gnorb-bbdb-link '((t :inherit org-link))
```

fixes my error mesage, but I am not sure if it gives the desired result.

**Comment by girzel** [comment]
Thanks! That was a dumb mistake. I've accepted your pull request, and will push a new version to Elpa shortly.
